# Generated by Django 3.1 on 2022-01-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_headersfooters_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersfooters',
            name='address',
        ),
    ]
