# Generated by Django 3.1 on 2022-01-19 19:37

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_headersfooters_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('short_info', tinymce.models.HTMLField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_by', models.CharField(blank=True, max_length=255, null=True)),
                ('event_by_image', models.ImageField(blank=True, null=True, upload_to='events_by')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_row_desc', tinymce.models.HTMLField(blank=True, null=True)),
                ('first_row_image', models.ImageField(blank=True, null=True, upload_to='home_page_first_row')),
                ('first_row_title', models.CharField(blank=True, max_length=255, null=True)),
                ('second_row_desc', tinymce.models.HTMLField(blank=True, null=True)),
                ('second_row_top_title_one', tinymce.models.HTMLField(blank=True, max_length=255, null=True)),
                ('second_row_top_title_two', tinymce.models.HTMLField(blank=True, max_length=255, null=True)),
                ('second_row_top_title_three', tinymce.models.HTMLField(blank=True, max_length=255, null=True)),
                ('second_row_top_title_four', tinymce.models.HTMLField(blank=True, max_length=255, null=True)),
                ('second_row_image_one', models.ImageField(blank=True, null=True, upload_to='home_page_second_row_top_image_one')),
                ('second_row_image_two', models.ImageField(blank=True, null=True, upload_to='home_page_second_row_top_image_two')),
                ('second_row_image_three', models.ImageField(blank=True, null=True, upload_to='home_page_second_row_top_image_three')),
                ('second_row_image_four', models.ImageField(blank=True, null=True, upload_to='home_page_second_row_top_image_four')),
                ('second_row_image_five', models.ImageField(blank=True, null=True, upload_to='home_page_second_row_top_image_five')),
                ('second_row_image_six', models.ImageField(blank=True, null=True, upload_to='home_page_second_row_top_image_six')),
                ('second_row_image_seven', models.ImageField(blank=True, null=True, upload_to='home_page_second_row_top_image_seven')),
                ('second_row_image_eight', models.ImageField(blank=True, null=True, upload_to='home_page_second_row_top_image_eight')),
                ('second_row_image_nine', models.ImageField(blank=True, null=True, upload_to='home_page_second_row_top_image_nine')),
                ('second_row_image_ten', models.ImageField(blank=True, null=True, upload_to='home_page_second_row_top_image_ten')),
                ('third_row_desc', tinymce.models.HTMLField(blank=True, null=True)),
                ('forth_row_desc', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', tinymce.models.HTMLField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('google_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=255)),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('color_choice_one', models.CharField(blank=True, max_length=255, null=True)),
                ('color_choice_two', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.period')),
            ],
        ),
    ]
