# Generated by Django 3.1 on 2022-01-27 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20220125_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='google_url',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='name',
        ),
        migrations.AddField(
            model_name='teachers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2(Section A)', '2(Section A)'), ('2(Section B)', '2(Section B)'), ('3(Section A)', '3(Section A)'), ('3(Section B)', '3(Section B)'), ('4(Section A)', '4(Section A)'), ('4(Section B)', '4(Section B)'), ('5(Section A)', '5(Section A)'), ('5(Section B)', '5(Section B)'), ('6(Section A)', '6(Section A)'), ('6(Section B)', '6(Section B)'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=255),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='results')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.students')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='homework')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('student', models.ManyToManyField(blank=True, to='core.Students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teachers')),
            ],
        ),
        migrations.AddField(
            model_name='teachers',
            name='class_name',
            field=models.ManyToManyField(blank=True, to='core.Grade'),
        ),
    ]
